=== m-klasen/XML/Aufgabe7/7.xsd
<xsd:schema>
	<xsd:element name="p"type="type1"/>
	<xsd:element name="bs"type="type2"/>

	<xsd:complexType name="type1">
		<xsd:sequence>
			<xsd:element name="a"type="xsd:string"/>
			<xsd:element ref="bs"/>
			<xsd:element name="c"type="xsd:string"minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="type2">
		<xsd:sequence>
			<xsd:element name="a"type="xsd:int"/>
			<xsd:element name="b"type="xsd:boolean"maxOccurs="4"/>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== m-klasen/XML/Aufgabe7/7.xml
<?xml version="1.1" encoding="UTF-8"?>

<p xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='7.xsd'>
	<a>1</a>
	<bs>
		<a>1</a>
		<b>3</b>
		<b>3</b>
		<b>5</b>
		<b>6</b>
	</bs>
	<c>2</c>
</p>
