=== m-klasen/XML/Aufgabe3/adrbuch.dtd
<!ELEMENT adressbuch (adresse)>
	<!ELEMENT adresse ((firma | person),strasse,plz ,(ort | state), (postcode | zipcode))>
	<!ATTLIST adresse land CDATA #IMPLIED>
		<!ELEMENT firma (firmenname,abteilung)>
			<!ELEMENT firmenname (#PCDATA)>
			<!ELEMENT abteilung (#PCDATA)>
		<!ATTLIST person titel CDATA #IMPLIED>
			<!ELEMENT vorname (#PCDATA)>
			<!ELEMENT nachname (#PCDATA)>
		<!ELEMENT strasse (#PCDATA)>
		<!ELEMENT plz (#PCDATA)>
		<!ELEMENT postcode (#PCDATA)>
		<!ELEMENT zipcode (#PCDATA)>
		<!ELEMENT ort (#PCDATA)>
		<!ELEMENT state (#PCDATA)>

=== m-klasen/XML/Aufgabe3/adrbuch.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE adressbuch SYSTEM "adrbuch.dtd">
<adressbuch>
<adresse>
	<firma>
		<firmenname>Uni Bonn</firmenname>
		<abteilung>InformatikIII</abteilung>
	</firma>
	<strasse>Römerstraße164</strasse>
	<plz>53117</plz>
	<ort>Bonn</ort>
</adresse>

<adresse>
	<person titel="Herr">
		<vorname>Manfred</vorname>
		<nachname>Mustermann</nachname>
	</person>
	<strasse>AmFriedhof11a</strasse>
	<plz>12345</plz>
	<ort>Irgendwo</ort>
</adresse>

<adresse land="uk">
	<person titel="Family">
		<nachname>Anyone</nachname>
	</person>
	<strasse>47EdenStreet</strasse>
	<ort>Cambridge</ort>
	<postcode>CB11JR</postcode>
</adresse>
<adresse land="us">
	<firma>
		<firmenname>OldWhiskeyBrewery</firmenname>
	</firma>
	<strasse>8OakAvenue</strasse>
	<ort>OldTown</ort>
	<state>PA</state>
	<zip>95819</zip>
</adresse>
</adressbuch>

=== m-klasen/XML/Aufgabe1/1.3.xml
<?xml  version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE adressbuch SYSTEM "adrbuch.dtd">
<adressbuch >
	<adresse>
		<firma>
			<firmenname >Uni  Bonn</firmenname >
			<abteilung >Informatik  III</abteilung >
		</firma>
		<strasse >Römerstraße  164</strasse >
		<plz>53117</plz>
		<ort>Bonn</ort>
	</adresse >
	<adresse >
		<person  titel="Herr">
			<vorname >Manfred </vorname >
			<nachname >Mustermann </nachname >
		</person >
		<strasse >Am  Friedhof  11a</strasse >
		<plz>12345</plz>
		<ort>Irgendwo </ort>
	</adresse >
	<adresse  land="uk">
		<person  titel="Family">
			<nachname >Anyone </nachname >
		</person >
		<strasse >47 Eden  Street </strasse >
		<ort>Cambridge </ort>
		<postcode >CB1 1JR</postcode >
	</adresse>
	<adresse  land="us">
		<firma>
			<firmenname >Old  Whiskey  Brewery </firmenname >
		</firma>
		<strasse >8 Oak  Avenue </strasse >
		<ort>Old  Town</ort>
		<state>PA</state>
		<zip>95819</zip>
	</adresse>
</adressbuch>
