=== m-klasen/XML/Aufgabe6/library.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="library">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="book" maxOccurs="unbounded">
						<xsd:complexType>
							<xsd:sequence>
								<xsd:element name="author-ref" type="xsd:string" maxOccurs="unbounded"/>
								<xsd:element name="title" type="xsd:string" maxOccurs="1"/>
								<xsd:element name="language" type="xsd:string" minOccurs="0"/>
								<xsd:element name="year" type="xsd:gYear" minOccurs="0"/> 
							</xsd:sequence>
						</xsd:complexType>
					<xsd:unique name="uniquebook">
						<xsd:selector xpath="./autor-ref"/>
						<xsd:field xpath="."/>
					</xsd:unique>
				</xsd:element>
				<xsd:element name="author" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="last-name" type="xsd:string" maxOccurs="unbounded" />
							<xsd:element name="first-name" type="xsd:string" maxOccurs="unbounded"/>
						</xsd:sequence>
						<xsd:attribute name="id" type="xsd:string" use="required"/>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
		<xsd:keyref name="authorreference" refer="authorRef">
			<xsd:selector xpath="./book/author-ref"/>
			<xsd:field xpath="."/>
		</xsd:keyref>
		<xsd:key name="authorRef">
			<xsd:selector xpath="./author"/>
			<xsd:field xpath="@id"/>
		</xsd:key>
	</xsd:element>
</xsd:schema>

=== m-klasen/XML/Aufgabe12/library.xml
<?xml version="1.1" encoding="UTF-8"?>

<library xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xsi:noNamespaceSchemaLocation='library.xsd'>

  <book>

    <book>
      <author-ref>G.Orwell</author-ref>
      <title>1984</title>
      <language>en</language>
      <year>1949</year>
    </book>

    <author-ref>J.K.Rowling</author-ref>
    <title>Harry Potter und der Stein der Weisen</title>
    <language>de</language>
    <year>1998</year>
  </book>

  <book>
    <author-ref>J.K.Rowling</author-ref>
    <title>Harry Potter und die Kammer des Schreckens</title>
    <language>de</language>
    <year>1999</year>
  </book>

  <book>
    <author-ref>M.Twain</author-ref>
    <title>Adventures of Huckleberry Finn</title>
    <language>en</language>
    <year>1884</year>
  </book>

  <book>
    <author-ref>T.Pratchett</author-ref>
    <title>The Colour of Magic</title>
    <year>1983</year>
  </book>

  <book>
    <author-ref>S.King</author-ref>
    <title>It</title>
    <language>en</language>
    <year>1986</year>
  </book>

  <book>
    <author-ref>T.Pratchett</author-ref>
    <author-ref>N.Gaiman</author-ref>
    <title>Good Omens: The Nice and Accurate Prophecies...</title>
    <language>en</language>
    <year>1990</year>
  </book> 
  
  <book>
    <author-ref>R.Munroe</author-ref>
    <title>What If?</title>
    <language>en</language>
    <year>2014</year>
  </book>

  <book>
    <author-ref>B.Bryson</author-ref>
    <title>A Short History of Nearly Everything</title>
    <language>en</language>
    <year>2003</year>
  </book>

  <book>
    <author-ref>B.Bryson</author-ref>
    <title>A Really Short History of Nearly Everything</title>
    <language>en</language>
    <year>2009</year>
  </book>

  <book>
    <author-ref>B.Bryson</author-ref>
    <title>One Summer: America, 1927</title>
    <language>en</language>
    <year>2013</year>
  </book>

  <book>
    <author-ref>A.Doerr</author-ref>
    <title>All the Light We Cannot See</title>
    <language>en</language>
    <year>2014</year>
  </book>

  <book>
    <author-ref>M.Tegmark</author-ref>
    <title>Our Mathematical Universe: My Quest for the Ultimate Nature of Reality</title>
    <language>en</language>
    <year>2014</year>
  </book>

  <book>
    <author-ref>N.Denne</author-ref>
    <title>DB2-Theorie und Praxis</title>
    <language>de</language>
    <year>2004</year>
  </book>

  

  <author id="G.Orwell">
    <last-name>Orwell</last-name>
    <first-name>George</first-name>
  </author>  


  <author id="J.K.Rowling">
    <last-name>Rowling</last-name>
    <first-name>Joanne K.</first-name>
  </author>

  <author id="M.Twain">
    <last-name>Twain</last-name>
    <first-name>Mark</first-name>
  </author>  

  <author id="T.Pratchett">
    <last-name>Pratchett</last-name>
    <first-name>Terry</first-name>
  </author>

  <author id="S.King">
    <last-name>King</last-name>
    <first-name>Stephen</first-name>
  </author> 

  <author id="N.Gaiman">
    <last-name>Gaiman</last-name>
    <first-name>Neil</first-name>
  </author>  
  
  <author id="R.Munroe">
    <last-name>Munroe</last-name>
    <first-name>Randall</first-name>
  </author>  

  <author id="B.Bryson">
    <last-name>Bryson</last-name>
    <first-name>Bill</first-name>
  </author>

  <author id="A.Doerr">
    <last-name>Doerr</last-name>
    <first-name>Anthony</first-name>
  </author>

  <author id="M.Tegmark">
    <last-name>Tegmark</last-name>
    <first-name>Max</first-name>
  </author>

  <author id="N.Denne">
    <last-name>Denne</last-name>
    <first-name>Norbert</first-name>
  </author>

</library>

=== m-klasen/XML/Aufgabe6/library.xml
<?xml version="1.1" encoding="UTF-8"?>

<library xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
	 xsi:noNamespaceSchemaLocation='library.xsd'>

  <book>
    <author-ref>J.K.Rowling</author-ref>
    <title>Harry Potter und der Stein der Weisen</title>
    <language>de</language>
    <year>1998</year>
  </book>

  <book>
    <author-ref>J.K.Rowling</author-ref>
    <title>Harry Potter und die Kammer des Schreckens</title>
    <language>de</language>
    <year>1999</year>
  </book>

  <book>
    <author-ref>T.Pratchett</author-ref>
    <title>The Colour of Magic</title>
    <year>1983</year>
  </book>

  <book>
    <author-ref>T.Pratchett</author-ref>
    <author-ref>N.Gaiman</author-ref>
    <title>Good Omens: The Nice and Accurate Prophecies...</title>
    <language>en</language>
  </book>

  <book>
    <author-ref>P. Thiel</author-ref>
    <title>Zero to One</title>
    <language>en</language>
    <year>2014</year>
  </book>

  <book>
    <author-ref>M. Tegmark</author-ref>
    <title>Life 3.0</title>
    <language>en</language>
  </book>

  <book>
    <author-ref>S. Finlay</author-ref>
    <title>AI and Machine Learning for Business</title>
    <language>en</language>
  </book>

  <book>
    <author-ref>Jordan B. Peterson</author-ref>
    <title>12 Rules for Life: An Antidote to Chaos</title>
    <language>en</language>
  </book>

  <book>
    <author-ref>Mark Manson</author-ref>
    <title>The Subtle Art of Not Giving a F*ck: A…</title>
    <language>en</language>
  </book>

  <book>
    <author-ref>Hans Rosling</author-ref>
    <title>Factfulness: Ten Reasons We're Wrong About…</title>
    <language>en</language>
  </book>

  <author id="J.K.Rowling">
    <last-name>Rowling</last-name>
    <first-name>Joanne K.</first-name>
  </author>

  <author id="N.Gaiman">
    <last-name>Gaiman</last-name>
    <first-name>Neil</first-name>
  </author>

  <author id="T.Pratchett">
    <last-name>Pratchett</last-name>
    <first-name>Terry</first-name>
  </author>

  <author id="S. Finlay">
    <last-name>Finlay</last-name>
    <first-name>Steven</first-name>
  </author>

  <author id="P. Thiel">
    <last-name>Thiel</last-name>
    <first-name>Peter</first-name>
  </author>

  <author id="M. Tegmark">
    <last-name>Tegmark</last-name>
    <first-name>Max</first-name>
  </author>

  <author id="Jordan B. Peterson">
    <last-name>Jordan B.</last-name>
    <first-name>Peterson</first-name>
  </author>

  <author id="Hans Rosling">
    <last-name>Hans</last-name>
    <first-name>Rosling</first-name>
  </author>

  <author id="Mark Manson">
    <last-name>Mark</last-name>
    <first-name>Manson</first-name>
  </author>

  







</library>
